name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-core:
    name: Test Core Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minnesota-immunization-core
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
        enable-cache: true
    
    - name: Install dependencies
      run: uv pip install --system ".[dev]"
    
    - name: Run tests
      run: uv run pytest

    - name: Run linting
      run: uv run ruff check .

  test-cli:
    name: Test CLI Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minnesota-immunization-cli
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
        enable-cache: true
    
    - name: Install dependencies
      run: uv pip install --system ".[dev]"
    
    - name: Run tests
      run: uv run pytest

    - name: Run linting
      run: uv run ruff check .

  test-cloud:
    name: Test Cloud Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minnesota-immunization-cloud
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
        enable-cache: true
    
    - name: Install dependencies
      run: uv pip install --system ".[dev]"
    
    - name: Run tests
      run: uv run pytest

    - name: Run linting
      run: uv run ruff check .