name: Publish Immunization Data Pipeline to PyPI
on:
  release:
    types: [ published ]

jobs:
  run-tests:
    uses: DillonOLeary/immunization-records-pipeline/.github/workflows/test-data-pipeline.yml@main
  
  run-linting:
    uses: DillonOLeary/immunization-records-pipeline/.github/workflows/lint-data-pipeline.yml@main

  publish:
    needs: [run-tests, run-linting]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies with Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd data-pipeline
        poetry install --without test,dev

    - name: Build package
      run: |
        cd data-pipeline
        poetry build

    - name: Test publish to PyPI
      run: |
        cd data-pipeline
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry publish -r testpypi -u __token__ -p ${{ secrets.PYPI_TEST_API_TOKEN }}

    - name: Publish to PyPI
      run: |
        cd data-pipeline
        poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

