name: Publish Immunization Data Pipeline to PyPI
on:
  release:
    types: [ published ]

jobs:
  # Call the test workflow to ensure all tests pass before deploying
  run-tests:
    uses: DillonOLeary/immunization-records-pipeline/.github/workflows/test-data-pipeline.yml@main

  publish:
    needs: run-tests  # Ensures tests pass before proceeding
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies with Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd data-pipeline
        poetry install --without test,dev

    - name: Build package
      run: |
        cd data-pipeline
        poetry build

    - name: Publish to PyPI
      run: |
        cd data-pipeline
        poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
